// Smoke test the Quantum Quest hub and complete available journey on desktop and mobile.
import fs from 'node:fs'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { chromium } from 'playwright'

const root = path.resolve(import.meta.dirname, '..')
const shotDir = path.join(root, 'smoke-shots')
const port = 4174
const base = `http://localhost:${port}`

fs.mkdirSync(shotDir, { recursive: true })
const server = spawn(`npx vite preview --port ${port} --strictPort`, { cwd: root, shell: true, stdio: 'inherit' })

async function waitForServer() {
  for (let attempt = 0; attempt < 40; attempt += 1) {
    await new Promise(resolve => setTimeout(resolve, 500))
    if (await fetch(base).then(response => response.ok).catch(() => false)) return
  }
  throw new Error('Quantum preview server did not start')
}

function collectErrors(page) {
  const errors = []
  page.on('pageerror', error => errors.push(`pageerror: ${error.message}`))
  page.on('console', message => {
    if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(`console: ${message.text()}`)
  })
  return errors
}

async function expectNoHorizontalOverflow(page, label) {
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
  if (overflow > 1) throw new Error(`${label} overflows horizontally by ${overflow}px`)
}

async function expectCanvasDrawn(page) {
  const colors = await page.locator('.qa-canvas').evaluate(canvas => {
    const context = canvas.getContext('2d')
    if (!context) return 0
    const samples = new Set()
    for (let row = 0; row < 30; row += 1) {
      for (let column = 0; column < 40; column += 1) {
        const x = Math.min(canvas.width - 1, Math.floor((column + 0.5) * canvas.width / 40))
        const y = Math.min(canvas.height - 1, Math.floor((row + 0.5) * canvas.height / 30))
        const pixel = context.getImageData(x, y, 1, 1).data
        samples.add(`${pixel[0]},${pixel[1]},${pixel[2]},${pixel[3]}`)
      }
    }
    return samples.size
  })
  if (colors < 4) throw new Error(`Quantum canvas looks blank (${colors} sampled colors)`)
}

await waitForServer()
const browser = await chromium.launch({ headless: true })

try {
  const desktop = await browser.newContext({ viewport: { width: 1280, height: 800 } })
  const desktopPage = await desktop.newPage()
  const desktopErrors = collectErrors(desktopPage)
  await desktopPage.goto(`${base}/`, { waitUntil: 'networkidle' })
  await desktopPage.getByRole('heading', { name: 'Build a quantum universe you can actually see.' }).waitFor()
  const lessonCount = await desktopPage.locator('.qa-lesson-card').count()
  if (lessonCount !== 35) throw new Error(`Expected 35 curriculum lessons, found ${lessonCount}`)
  const playableCount = await desktopPage.locator('.qa-playable').count()
  if (playableCount !== 29) throw new Error(`Expected 29 playable lessons, found ${playableCount}`)
  await expectNoHorizontalOverflow(desktopPage, 'desktop hub')
  await desktopPage.screenshot({ path: path.join(shotDir, 'quantum-hub-desktop.png'), fullPage: false })
  await desktopPage.goto(`${base}/the-wavefunction`, { waitUntil: 'networkidle' })
  await desktopPage.getByRole('heading', { name: 'The wavefunction describes a state, not a blurry object' }).waitFor()
  await expectCanvasDrawn(desktopPage)
  await expectNoHorizontalOverflow(desktopPage, 'desktop wavefunction lesson')
  await desktopPage.screenshot({ path: path.join(shotDir, 'wavefunction-lesson-desktop.png'), fullPage: false })
  await desktopPage.goto(`${base}/atomic-orbitals`, { waitUntil: 'networkidle' })
  await desktopPage.getByRole('heading', { name: 'An orbital is a probability shape, not an orbit' }).waitFor()
  await desktopPage.getByRole('button', { name: /p orbital/ }).click()
  await desktopPage.waitForTimeout(250)
  if (desktopErrors.length) throw new Error(desktopErrors.join(' | '))
  await expectCanvasDrawn(desktopPage)
  await expectNoHorizontalOverflow(desktopPage, 'desktop orbital lesson')
  await desktopPage.screenshot({ path: path.join(shotDir, 'orbital-lesson-desktop.png'), fullPage: false })
  await desktopPage.goto(`${base}/bells-experiment`, { waitUntil: 'networkidle' })
  await desktopPage.getByRole('heading', { name: 'Could each particle carry a private answer sheet?' }).waitFor()
  await desktopPage.getByRole('button', { name: /Bell pair/ }).click()
  await desktopPage.waitForTimeout(250)
  await expectCanvasDrawn(desktopPage)
  await expectNoHorizontalOverflow(desktopPage, 'desktop Bell experiment')
  await desktopPage.screenshot({ path: path.join(shotDir, 'bell-experiment-desktop.png'), fullPage: false })
  await desktopPage.goto(`${base}/quantum-gates-and-circuits`, { waitUntil: 'networkidle' })
  await desktopPage.getByRole('heading', { name: 'A quantum gate rotates amplitudes without reading them' }).waitFor()
  await desktopPage.getByRole('button', { name: /Z gate/ }).click()
  await desktopPage.waitForTimeout(250)
  await expectCanvasDrawn(desktopPage)
  await expectNoHorizontalOverflow(desktopPage, 'desktop quantum gate lesson')
  await desktopPage.screenshot({ path: path.join(shotDir, 'quantum-gate-desktop.png'), fullPage: false })
  if (desktopErrors.length) throw new Error(desktopErrors.join(' | '))
  await desktop.close()

  const compact = await browser.newContext({ viewport: { width: 320, height: 568 }, isMobile: true, hasTouch: true })
  const compactPage = await compact.newPage()
  const compactErrors = collectErrors(compactPage)
  await compactPage.goto(`${base}/semiconductors`, { waitUntil: 'networkidle' })
  await compactPage.getByRole('heading', { name: 'Atomic levels broaden into energy bands' }).waitFor()
  await compactPage.getByRole('button', { name: 'Continue →' }).click()
  await expectNoHorizontalOverflow(compactPage, 'compact semiconductor controls')
  await compactPage.screenshot({ path: path.join(shotDir, 'semiconductor-doping-compact.png'), fullPage: false })
  await compactPage.goto(`${base}/quantum-gates-and-circuits`, { waitUntil: 'networkidle' })
  await compactPage.getByRole('heading', { name: 'A quantum gate rotates amplitudes without reading them' }).waitFor()
  await expectCanvasDrawn(compactPage)
  await expectNoHorizontalOverflow(compactPage, 'compact quantum gate lesson')
  await compactPage.goto(`${base}/quantum-cryptography`, { waitUntil: 'networkidle' })
  await compactPage.getByRole('heading', { name: 'Two incompatible bases encode the same bit values' }).waitFor()
  await expectCanvasDrawn(compactPage)
  await expectNoHorizontalOverflow(compactPage, 'compact QKD lesson')
  if (compactErrors.length) throw new Error(compactErrors.join(' | '))
  await compact.close()

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  const page = await mobile.newPage()
  const errors = collectErrors(page)
  await page.goto(`${base}/`, { waitUntil: 'networkidle' })
  await expectNoHorizontalOverflow(page, 'mobile hub')
  await page.getByRole('link', { name: /Start first journey/ }).click()
  await page.getByRole('heading', { name: 'First, shrink your point of view' }).waitFor()
  await page.waitForTimeout(500)
  await page.screenshot({ path: path.join(shotDir, 'quantum-lesson-mobile-start.png'), fullPage: false })
  await expectCanvasDrawn(page)
  await page.locator('input[type="range"]').fill('4')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Wave' }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Burst 25' }).click()
  await page.getByText('Detector has recorded 25 events.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Path detector off/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure electron' }).click()
  await page.getByText(/Detector clicked on the/).waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Single detections are discrete/ }).click()
  await page.getByRole('button', { name: 'Check answer →' }).click()
  await page.getByText(/Exactly. Quantum theory predicts/).waitFor()
  await page.screenshot({ path: path.join(shotDir, 'quantum-check-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'Your first quantum model is alive' }).waitFor()
  await page.waitForTimeout(500)
  await expectCanvasDrawn(page)
  await page.screenshot({ path: path.join(shotDir, 'quantum-summary-mobile.png'), fullPage: false })
  await expectNoHorizontalOverflow(page, 'mobile summary')
  let completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (!completed.includes('the-quantum-rules-change')) throw new Error('First lesson completion was not saved')

  await page.getByRole('button', { name: 'Start next lesson →' }).click()
  await page.getByRole('heading', { name: 'A particle carries its story along one path' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByLabel('Particle speed').fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Wave frequency').fill('70')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Wave/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Different experiments reveal/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByText(/The evidence contains particle-like events/).waitFor()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'Two models, one important limitation' }).waitFor()
  await page.screenshot({ path: path.join(shotDir, 'foundation-lesson-two-mobile.png'), fullPage: false })
  await expectNoHorizontalOverflow(page, 'mobile lesson two summary')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (!completed.includes('classical-particles-and-waves')) throw new Error('Second lesson completion was not saved')

  await page.getByRole('button', { name: 'Start next lesson →' }).click()
  await page.getByRole('heading', { name: 'Classical energy looks like a ramp' }).waitFor()
  await page.getByRole('button', { name: /Quantum steps/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Allowed level').fill('4')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Excited level').fill('3')
  await page.getByRole('button', { name: 'Release one photon →' }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Only particular energy levels/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A dim light still arrives in whole detections' }).waitFor()
  await page.getByLabel('Brightness').fill('5')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Photon color' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Photon energy').fill('70')
  await page.getByRole('button', { name: 'Fire photon →' }).click()
  await page.getByText('An electron escaped the surface.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /More low-energy photons arrive/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Source, openings, screen' }).waitFor()
  await page.screenshot({ path: path.join(shotDir, 'double-slit-builder-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: /One slit/ }).click()
  await page.getByRole('button', { name: /Two slits/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Relative phase').fill('60')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Send 50' }).click()
  await page.getByText('50 photon events recorded.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /No path record/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /It stores information/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Four clues point to one new framework' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /The amplitudes for alternative paths/ }).click()
  await page.getByRole('radio', { name: /Its allowed energies are discrete/ }).click()
  await page.getByRole('radio', { name: /Storing reliable which-path information/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'You have left the classical world' }).waitFor()
  await expectNoHorizontalOverflow(page, 'mobile foundations complete')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (completed.length !== 6) throw new Error(`Expected 6 completed foundation lessons, found ${completed.length}`)
  await page.screenshot({ path: path.join(shotDir, 'foundation-stage-complete-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'The wavefunction describes a state, not a blurry object' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByRole('slider', { name: 'Packet center' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Probability/ }).click()
  await page.waitForTimeout(200)
  await expectCanvasDrawn(page)
  await page.screenshot({ path: path.join(shotDir, 'wavefunction-probability-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Global phase' }).fill('65')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /An amplitude with size and phase/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A superposition combines possible states' }).waitFor()
  await page.getByRole('slider', { name: 'Outcome 1 probability' }).fill('70')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Relative phase' }).fill('50')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /X basis/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /relative phase and can interfere/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Preparation sets probabilities, not a secret answer' }).waitFor()
  await page.getByRole('slider', { name: 'Probability of outcome 1' }).fill('75')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure 50' }).click()
  await page.getByText('50 outcomes recorded.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure state' }).click()
  await page.getByText(/recorded. The state now matches it./).waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /The outcome-1 state/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A narrow position needs a broad momentum range' }).waitFor()
  await page.getByRole('slider', { name: 'Position width' }).fill('20')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Wave components' }).fill('9')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Momentum/ }).click()
  await page.getByRole('slider', { name: 'Position width' }).fill('75')
  await page.screenshot({ path: path.join(shotDir, 'uncertainty-dual-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Localization requires combining many wavelengths/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A state is a direction in an abstract space' }).waitFor()
  await page.getByRole('slider', { name: 'State angle' }).fill('40')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /X basis/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Relative phase' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Its amplitude coordinates change/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Potential energy shapes the possibilities' }).waitFor()
  await page.getByRole('button', { name: /Box/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Evolution speed' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Together/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Packet energy' }).fill('70')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /smooth time evolution of the wavefunction/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'You can speak the quantum language' }).waitFor()
  await expectNoHorizontalOverflow(page, 'mobile quantum language complete')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (completed.length !== 12) throw new Error(`Expected 12 completed lessons, found ${completed.length}`)
  await page.screenshot({ path: path.join(shotDir, 'language-stage-complete-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Walls turn traveling possibilities into standing waves' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByRole('slider', { name: 'Box width' }).fill('75')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Quantum level' }).fill('4')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Quantum level' }).fill('5')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Only certain standing-wave patterns/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Build a barrier higher than the particle’s energy' }).waitFor()
  await page.getByRole('slider', { name: 'Barrier height' }).fill('85')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Packet energy' }).fill('55')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Barrier width' }).fill('70')
  await page.getByRole('button', { name: 'Send 100 particles' }).click()
  await page.getByText(/of 100 particles tunneled/).waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /wavefunction can retain nonzero amplitude/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'An orbital is a probability shape, not an orbit' }).waitFor()
  await page.getByRole('button', { name: /p orbital/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Orbital level' }).fill('4')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Sample 60' }).click()
  await page.getByText('60 orbital detections recorded.').waitFor()
  await expectCanvasDrawn(page)
  await page.screenshot({ path: path.join(shotDir, 'orbital-sampling-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /three-dimensional quantum state/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A magnetic field splits spin into two outcomes' }).waitFor()
  await page.getByRole('slider', { name: 'Magnet axis' }).fill('50')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Spin state angle' }).fill('40')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /X axis/ }).click()
  await page.getByRole('button', { name: 'Measure 50' }).click()
  await page.getByText(/50 spin outcomes recorded along X/).waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /quantum state relative to possible measurement axes/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Identical quantum particles cannot be tracked by identity' }).waitFor()
  await page.getByRole('button', { name: /Boson/ }).click()
  await page.getByRole('button', { name: /Fermion/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Fermion count' }).fill('8')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Bosons/ }).click()
  await page.getByRole('button', { name: /Fermions/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /two electrons can differ by spin/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Electron states organize into shells and subshells' }).waitFor()
  await page.getByRole('slider', { name: 'Electron count' }).fill('18')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'p subshell electrons' }).fill('6')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Atomic number' }).fill('18')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Bound wavefunctions permit only certain states/ }).click()
  await page.getByRole('radio', { name: /two available opposite spin states/ }).click()
  await page.getByRole('radio', { name: /repeat similar outer-electron configurations/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'Quantum rules now build ordinary matter' }).waitFor()
  await expectCanvasDrawn(page)
  await expectNoHorizontalOverflow(page, 'mobile atoms and matter complete')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (completed.length !== 18) throw new Error(`Expected 18 completed lessons, found ${completed.length}`)
  await page.screenshot({ path: path.join(shotDir, 'matter-stage-complete-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Two particles need one joint state description' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByRole('button', { name: /01/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Pair correlation' }).fill('85')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure 80 pairs' }).click()
  await page.getByText('80 joint outcomes recorded.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /often return matching results/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Entanglement makes the pair the fundamental system' }).waitFor()
  await page.getByRole('slider', { name: 'Entanglement strength' }).fill('100')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /X axis/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /X axis/ }).click()
  await page.getByRole('button', { name: 'Measure 80 pairs' }).click()
  await page.getByText('80 Bell-pair outcomes compared.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /complete state contains joint amplitudes/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Could each particle carry a private answer sheet?' }).waitFor()
  await page.getByRole('button', { name: /Bell pair/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Detector angle' }).fill('55')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Bell pair/ }).click()
  await page.getByRole('button', { name: 'Run 200 trials' }).click()
  await page.getByText(/of 200 Bell-game trials won/).waitFor()
  await expectCanvasDrawn(page)
  await page.screenshot({ path: path.join(shotDir, 'bell-game-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Local hidden-variable models/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Interference needs branches to keep a phase relationship' }).waitFor()
  await page.getByRole('slider', { name: 'Environmental coupling' }).fill('85')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Environment records' }).fill('24')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Decoherence level' }).fill('95')
  await expectCanvasDrawn(page)
  await page.screenshot({ path: path.join(shotDir, 'decoherence-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Phase information becomes distributed/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A microscopic event can control a macroscopic record' }).waitFor()
  await page.getByRole('slider', { name: 'Decay probability' }).fill('50')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Branches/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Environmental contact' }).fill('95')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /tension in applying quantum superposition/ }).click()
  await page.getByRole('radio', { name: /interference between macroscopic alternatives/ }).click()
  await page.getByRole('radio', { name: /correlates the observer with an already strongly decohered/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'You can trace quantum relationships into the classical world' }).waitFor()
  await expectCanvasDrawn(page)
  await expectNoHorizontalOverflow(page, 'mobile entanglement complete')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (completed.length !== 23) throw new Error(`Expected 23 completed lessons, found ${completed.length}`)
  await page.screenshot({ path: path.join(shotDir, 'entanglement-stage-complete-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Pumping lifts atoms into excited states' }).waitFor()
  await page.getByRole('slider', { name: 'Pump rate' }).fill('85')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Excited population' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Release seed photon →' }).click()
  await page.getByText(/photons now reinforce/).waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Stimulated emission adds photons/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Atomic levels broaden into energy bands' }).waitFor()
  await page.getByRole('slider', { name: 'Band gap' }).fill('65')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /n-type/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Gate voltage' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /band gap and carrier population/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A field creates a tiny spin population imbalance' }).waitFor()
  await page.getByRole('slider', { name: 'Magnetic field' }).fill('85')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Radio frequency' }).fill('50')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Excite sample →' }).click()
  await page.getByText('Signal acquisition 1 recorded.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Precessing net magnetization induces/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A qubit stores a direction in quantum state space' }).waitFor()
  await page.getByRole('button', { name: /Qubit/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Qubit rotation' }).fill('65')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure 100 qubits' }).click()
  await page.getByText('100 qubit measurements recorded.').waitFor()
  await expectCanvasDrawn(page)
  await expectNoHorizontalOverflow(page, 'mobile qubit histogram')
  await page.screenshot({ path: path.join(shotDir, 'qubit-histogram-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /controllable quantum state with amplitudes/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A quantum gate rotates amplitudes without reading them' }).waitFor()
  await page.getByRole('button', { name: /H gate/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /H-Z-H/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /H-Z-H/ }).click()
  await page.getByRole('button', { name: 'Run 100 shots' }).click()
  await page.getByText('100 circuit shots recorded.').waitFor()
  await expectCanvasDrawn(page)
  await expectNoHorizontalOverflow(page, 'mobile circuit results')
  await page.screenshot({ path: path.join(shotDir, 'circuit-results-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Transform amplitudes and phases/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Two incompatible bases encode the same bit values' }).waitFor()
  await page.getByRole('button', { name: /Diagonal/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Direct quantum channel/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Transmit 120 sifted bits' }).click()
  await page.getByText(/errors found in 120 sifted bits/).waitFor()
  await expectCanvasDrawn(page)
  await expectNoHorizontalOverflow(page, 'mobile QKD key')
  await page.screenshot({ path: path.join(shotDir, 'qkd-key-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /stimulated emission more likely/ }).click()
  await page.getByRole('radio', { name: /Later gates recombine amplitudes/ }).click()
  await page.getByRole('radio', { name: /Wrong-basis measurements introduce/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'Quantum physics is already an engineering toolkit' }).waitFor()
  await expectCanvasDrawn(page)
  await expectNoHorizontalOverflow(page, 'mobile applications complete')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (completed.length !== 29) throw new Error(`Expected 29 completed lessons, found ${completed.length}`)
  await page.screenshot({ path: path.join(shotDir, 'applications-stage-complete-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Return to course map →' }).click()
  await page.getByText('29/35 lessons').waitFor()
  await page.waitForFunction(() => window.scrollY === 0)
  const hubScroll = await page.evaluate(() => window.scrollY)
  if (hubScroll !== 0) throw new Error(`Course map returned at scroll position ${hubScroll}`)
  if (errors.length) throw new Error(errors.join(' | '))
  await mobile.close()
  console.log('Quantum smoke passed: 35-lesson hub, 29 playable lessons, progress, and complete mobile journey')
} finally {
  await browser.close()
  server.kill()
}
