// Smoke test the Quantum Quest hub and first journey on desktop and mobile.
import fs from 'node:fs'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { chromium } from 'playwright'

const root = path.resolve(import.meta.dirname, '..')
const shotDir = path.join(root, 'smoke-shots')
const port = 4174
const base = `http://localhost:${port}`

fs.mkdirSync(shotDir, { recursive: true })
const server = spawn(`npx vite preview --port ${port} --strictPort`, { cwd: root, shell: true, stdio: 'inherit' })

async function waitForServer() {
  for (let attempt = 0; attempt < 40; attempt += 1) {
    await new Promise(resolve => setTimeout(resolve, 500))
    if (await fetch(base).then(response => response.ok).catch(() => false)) return
  }
  throw new Error('Quantum preview server did not start')
}

function collectErrors(page) {
  const errors = []
  page.on('pageerror', error => errors.push(`pageerror: ${error.message}`))
  page.on('console', message => {
    if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(`console: ${message.text()}`)
  })
  return errors
}

async function expectNoHorizontalOverflow(page, label) {
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
  if (overflow > 1) throw new Error(`${label} overflows horizontally by ${overflow}px`)
}

async function expectCanvasDrawn(page) {
  const colors = await page.locator('.qa-canvas').evaluate(canvas => {
    const context = canvas.getContext('2d')
    if (!context) return 0
    const samples = new Set()
    for (let row = 0; row < 30; row += 1) {
      for (let column = 0; column < 40; column += 1) {
        const x = Math.min(canvas.width - 1, Math.floor((column + 0.5) * canvas.width / 40))
        const y = Math.min(canvas.height - 1, Math.floor((row + 0.5) * canvas.height / 30))
        const pixel = context.getImageData(x, y, 1, 1).data
        samples.add(`${pixel[0]},${pixel[1]},${pixel[2]},${pixel[3]}`)
      }
    }
    return samples.size
  })
  if (colors < 4) throw new Error(`Quantum canvas looks blank (${colors} sampled colors)`)
}

await waitForServer()
const browser = await chromium.launch({ headless: true })

try {
  const desktop = await browser.newContext({ viewport: { width: 1280, height: 800 } })
  const desktopPage = await desktop.newPage()
  const desktopErrors = collectErrors(desktopPage)
  await desktopPage.goto(`${base}/`, { waitUntil: 'networkidle' })
  await desktopPage.getByRole('heading', { name: 'Build a quantum universe you can actually see.' }).waitFor()
  const lessonCount = await desktopPage.locator('.qa-lesson-card').count()
  if (lessonCount !== 35) throw new Error(`Expected 35 curriculum lessons, found ${lessonCount}`)
  const playableCount = await desktopPage.locator('.qa-playable').count()
  if (playableCount !== 12) throw new Error(`Expected 12 playable lessons, found ${playableCount}`)
  await expectNoHorizontalOverflow(desktopPage, 'desktop hub')
  await desktopPage.screenshot({ path: path.join(shotDir, 'quantum-hub-desktop.png'), fullPage: false })
  await desktopPage.goto(`${base}/the-wavefunction`, { waitUntil: 'networkidle' })
  await desktopPage.getByRole('heading', { name: 'The wavefunction describes a state, not a blurry object' }).waitFor()
  await expectCanvasDrawn(desktopPage)
  await expectNoHorizontalOverflow(desktopPage, 'desktop wavefunction lesson')
  await desktopPage.screenshot({ path: path.join(shotDir, 'wavefunction-lesson-desktop.png'), fullPage: false })
  if (desktopErrors.length) throw new Error(desktopErrors.join(' | '))
  await desktop.close()

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  const page = await mobile.newPage()
  const errors = collectErrors(page)
  await page.goto(`${base}/`, { waitUntil: 'networkidle' })
  await expectNoHorizontalOverflow(page, 'mobile hub')
  await page.getByRole('link', { name: /Start first journey/ }).click()
  await page.getByRole('heading', { name: 'First, shrink your point of view' }).waitFor()
  await page.waitForTimeout(500)
  await page.screenshot({ path: path.join(shotDir, 'quantum-lesson-mobile-start.png'), fullPage: false })
  await expectCanvasDrawn(page)
  await page.locator('input[type="range"]').fill('4')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Wave' }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Burst 25' }).click()
  await page.getByText('Detector has recorded 25 events.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Path detector off/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure electron' }).click()
  await page.getByText(/Detector clicked on the/).waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Single detections are discrete/ }).click()
  await page.getByRole('button', { name: 'Check answer →' }).click()
  await page.getByText(/Exactly. Quantum theory predicts/).waitFor()
  await page.screenshot({ path: path.join(shotDir, 'quantum-check-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'Your first quantum model is alive' }).waitFor()
  await page.waitForTimeout(500)
  await expectCanvasDrawn(page)
  await page.screenshot({ path: path.join(shotDir, 'quantum-summary-mobile.png'), fullPage: false })
  await expectNoHorizontalOverflow(page, 'mobile summary')
  let completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (!completed.includes('the-quantum-rules-change')) throw new Error('First lesson completion was not saved')

  await page.getByRole('button', { name: 'Start next lesson →' }).click()
  await page.getByRole('heading', { name: 'A particle carries its story along one path' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByLabel('Particle speed').fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Wave frequency').fill('70')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Wave/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Different experiments reveal/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByText(/The evidence contains particle-like events/).waitFor()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'Two models, one important limitation' }).waitFor()
  await page.screenshot({ path: path.join(shotDir, 'foundation-lesson-two-mobile.png'), fullPage: false })
  await expectNoHorizontalOverflow(page, 'mobile lesson two summary')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (!completed.includes('classical-particles-and-waves')) throw new Error('Second lesson completion was not saved')

  await page.getByRole('button', { name: 'Start next lesson →' }).click()
  await page.getByRole('heading', { name: 'Classical energy looks like a ramp' }).waitFor()
  await page.getByRole('button', { name: /Quantum steps/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Allowed level').fill('4')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Excited level').fill('3')
  await page.getByRole('button', { name: 'Release one photon →' }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Only particular energy levels/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A dim light still arrives in whole detections' }).waitFor()
  await page.getByLabel('Brightness').fill('5')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Photon color' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Photon energy').fill('70')
  await page.getByRole('button', { name: 'Fire photon →' }).click()
  await page.getByText('An electron escaped the surface.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /More low-energy photons arrive/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Source, openings, screen' }).waitFor()
  await page.screenshot({ path: path.join(shotDir, 'double-slit-builder-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: /One slit/ }).click()
  await page.getByRole('button', { name: /Two slits/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByLabel('Relative phase').fill('60')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Send 50' }).click()
  await page.getByText('50 photon events recorded.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /No path record/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /It stores information/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Four clues point to one new framework' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /The amplitudes for alternative paths/ }).click()
  await page.getByRole('radio', { name: /Its allowed energies are discrete/ }).click()
  await page.getByRole('radio', { name: /Storing reliable which-path information/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'You have left the classical world' }).waitFor()
  await expectNoHorizontalOverflow(page, 'mobile foundations complete')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (completed.length !== 6) throw new Error(`Expected 6 completed foundation lessons, found ${completed.length}`)
  await page.screenshot({ path: path.join(shotDir, 'foundation-stage-complete-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'The wavefunction describes a state, not a blurry object' }).waitFor()
  await expectCanvasDrawn(page)
  await page.getByRole('slider', { name: 'Packet center' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Probability/ }).click()
  await page.waitForTimeout(200)
  await expectCanvasDrawn(page)
  await page.screenshot({ path: path.join(shotDir, 'wavefunction-probability-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Global phase' }).fill('65')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /An amplitude with size and phase/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A superposition combines possible states' }).waitFor()
  await page.getByRole('slider', { name: 'Outcome 1 probability' }).fill('70')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Relative phase' }).fill('50')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /X basis/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /relative phase and can interfere/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Preparation sets probabilities, not a secret answer' }).waitFor()
  await page.getByRole('slider', { name: 'Probability of outcome 1' }).fill('75')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure 50' }).click()
  await page.getByText('50 outcomes recorded.').waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: 'Measure state' }).click()
  await page.getByText(/recorded. The state now matches it./).waitFor()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /The outcome-1 state/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A narrow position needs a broad momentum range' }).waitFor()
  await page.getByRole('slider', { name: 'Position width' }).fill('20')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Wave components' }).fill('9')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Momentum/ }).click()
  await page.getByRole('slider', { name: 'Position width' }).fill('75')
  await page.screenshot({ path: path.join(shotDir, 'uncertainty-dual-mobile.png'), fullPage: false })
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Localization requires combining many wavelengths/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'A state is a direction in an abstract space' }).waitFor()
  await page.getByRole('slider', { name: 'State angle' }).fill('40')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /X basis/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Relative phase' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /Its amplitude coordinates change/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('button', { name: 'Start next lesson →' }).click()

  await page.getByRole('heading', { name: 'Potential energy shapes the possibilities' }).waitFor()
  await page.getByRole('button', { name: /Box/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Evolution speed' }).fill('80')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('button', { name: /Together/ }).click()
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('slider', { name: 'Packet energy' }).fill('70')
  await page.getByRole('button', { name: 'Continue →' }).click()
  await page.getByRole('radio', { name: /smooth time evolution of the wavefunction/ }).click()
  await page.getByRole('button', { name: 'Check model →' }).click()
  await page.getByRole('button', { name: 'See summary →' }).click()
  await page.getByRole('heading', { name: 'You can speak the quantum language' }).waitFor()
  await expectNoHorizontalOverflow(page, 'mobile quantum language complete')
  completed = await page.evaluate(() => JSON.parse(localStorage.getItem('quantum-quest-completed-lessons') || '[]'))
  if (completed.length !== 12) throw new Error(`Expected 12 completed lessons, found ${completed.length}`)
  await page.getByRole('button', { name: 'Return to course map →' }).click()
  await page.getByText('12/35 lessons').waitFor()
  await page.waitForFunction(() => window.scrollY === 0)
  const hubScroll = await page.evaluate(() => window.scrollY)
  if (hubScroll !== 0) throw new Error(`Course map returned at scroll position ${hubScroll}`)
  await page.screenshot({ path: path.join(shotDir, 'language-stage-complete-mobile.png'), fullPage: false })
  if (errors.length) throw new Error(errors.join(' | '))
  await mobile.close()
  console.log('Quantum smoke passed: 35-lesson hub, 12 playable lessons, progress, and complete mobile journey')
} finally {
  await browser.close()
  server.kill()
}
